syntax = "proto3";
import "common.proto";
package declaration;

// ENTITÉ PRINCIPALE
message Declaration {
  string id           = 1;
  string client_id    = 2;
  string client_nom   = 3;
  string comptable_id = 4;
  string type         = 5;  // TVA | IS | IRPP | CNSS
  string periode      = 6;
  double montant      = 7;
  string statut       = 8;  // brouillon | soumise | validee
  string validated_by = 9;
  string validated_at = 10;
  string created_at   = 11;
}

// REQUESTS
message CreateDeclarationRequest {
  string client_id    = 1;
  string client_nom   = 2;
  string comptable_id = 3;
  string type         = 4;
  string periode      = 5;
  double montant      = 6;
}

message UpdateDeclarationRequest {
  string declaration_id = 1;
  double montant        = 2;
  string periode        = 3;
}

message DeleteDeclarationRequest {
  string declaration_id = 1;
}

message ValidateDeclarationRequest {
  string declaration_id = 1;
  string comptable_id   = 2;
}

message GetDeclarationRequest {
  string id = 1;
}

message GetClientDeclarationsRequest {
  string client_id = 1;
}

//RESPONSES
message DeclarationResponse {
  Declaration declaration = 1;
}

message DeclarationsListResponse {
  repeated Declaration declarations = 1;
}

message DeleteResponse {
  bool   success = 1;
  string message = 2;
}

//SERVICE
service DeclarationService {
  rpc CreateDeclaration     (CreateDeclarationRequest)     returns (DeclarationResponse);
  rpc UpdateDeclaration     (UpdateDeclarationRequest)     returns (DeclarationResponse);
  rpc DeleteDeclaration     (DeleteDeclarationRequest)     returns (DeleteResponse);
  rpc ValidateDeclaration   (ValidateDeclarationRequest)   returns (DeclarationResponse);
  rpc GetDeclaration        (GetDeclarationRequest)        returns (DeclarationResponse);
  rpc GetClientDeclarations (GetClientDeclarationsRequest) returns (DeclarationsListResponse);
  rpc GetAllDeclarations    (common.EmptyRequest)          returns (DeclarationsListResponse);
}
